# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/wulian/DD/Image_FD-SOC/KWS-SOC.srcs/sources_1/ip/pic_detec_0/pic_detec_0.xci
# IP: The module: 'pic_detec_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/wulian/DD/Image_FD-SOC/KWS-SOC.srcs/sources_1/ip/pic_detec_0/constraints/pic_detec_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pic_detec_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/wulian/DD/Image_FD-SOC/KWS-SOC.srcs/sources_1/ip/pic_detec_0/pic_detec_0.xci
# IP: The module: 'pic_detec_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/wulian/DD/Image_FD-SOC/KWS-SOC.srcs/sources_1/ip/pic_detec_0/constraints/pic_detec_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pic_detec_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
