// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module delta2 (
        ap_ready,
        A,
        B,
        m,
        n,
        ap_return
);


output   ap_ready;
input  [15:0] A;
input  [15:0] B;
input  [2:0] m;
input  [2:0] n;
output  [0:0] ap_return;

wire  signed [15:0] sext_ln6_fu_36_p1;
wire  signed [15:0] sext_ln6_1_fu_46_p1;
wire   [0:0] icmp_ln6_fu_40_p2;
wire   [0:0] icmp_ln6_1_fu_50_p2;

assign ap_ready = 1'b1;

assign ap_return = (icmp_ln6_fu_40_p2 & icmp_ln6_1_fu_50_p2);

assign icmp_ln6_1_fu_50_p2 = ((sext_ln6_1_fu_46_p1 == B) ? 1'b1 : 1'b0);

assign icmp_ln6_fu_40_p2 = ((sext_ln6_fu_36_p1 == A) ? 1'b1 : 1'b0);

assign sext_ln6_1_fu_46_p1 = $signed(n);

assign sext_ln6_fu_36_p1 = $signed(m);

endmodule //delta2
